config/routes.rb
PancakeApp::Application.routes.draw do
  root 'pancake_pages#index'
  match '/faq',		to: 'pancake_pages#faq',	via: 'get'
  match '/about',	to: 'pancake_pages#about',	via: 'get'
  match '/blog',	to: 'pancake_pages#blog',	via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pancake_pages_controller.rb
class PancakePagesController < ApplicationController
  def index
  end

  def faq
  end

  def about
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.		#Documentation comment
  def full_title(page_title)				#Method definition
    base_title = "My pancake: Reimagine & Redefine"	#Variable assignment
    if page_title.empty?				#Boolean test
      base_title					#Implicit return
    else
      "#{base_title} | #{page_title}"			# String interpolation
    end
  end
end

app/helpers/pancake_pages_helper.rb
module PancakePagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Liang Zheng Gooi
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li>Copyright 2014</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "my pancake", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Blog",    blog_path %></li>
          <li><%= link_to "FAQ",    faq_path %></li>
          <li><%= link_to "About Us", about_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pancake_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	We hope that people will be able to make beautiful pancakes by their own, 
	so we provide and share all interesting ways to make pancakes.
</p>
<img src="assets/allie_burger.jpg" alt="baby with burger pancake" class="clearfix img-rounded">

app/views/pancake_pages/blog.html.erb
<%provide(:title, 'Blog')%>
<h1>Blog</h1>
<p>
  This page is still under construction, check back again for more delicious pancakes!
</p>

app/views/pancake_pages/faq.html.erb
<%provide(:title, 'FAQ')%>
<h1>Frequently Asked Questions</h1>
<p>
	Q: Why is this website exist? </br>
	A: We want to spread the love of making pancakes.
</p>

app/views/pancake_pages/index.html.erb
<div class = "center hero-unit">
  <h1>Welcome to My Pancake</h1>
  
  <h2>
    This is the homepage of My Pancake. The way pancake supposed to be made.
  </h2>

  <%= link_to "Learn more", blog_path, class: "btn btn-large btn-primary" %>
</div>

<img src="assets/millenium_falcon_pancake.jpg" alt="millenium falcon" class="center img-rounded">
<img src="assets/star_wars_pancakes.jpg" alt="star wars" class="center img-rounded">